import { Bebas_Neue, Be_Vietnam_Pro } from 'next/font/google'
import "./globals.css";
import Navbar from '@/components/Navbar';



const bebas = Bebas_Neue({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-display',
})

const vietnam = Be_Vietnam_Pro({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-body',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${bebas.variable} ${vietnam.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
